# Project 1: Analyzing the impact of Covid on Microwd's portfolio
The objective of this exploratory analysis using Spark was to discover challenges and opportunities for Microwd in Latin America through an exploratory analysis of Covid-19 using Spark.
Microwd is a fintech that connects female entrepreneurs in Latin America who need a microcredit for their businesses with investors in Europe who want profitability with a positive social impact. https://www.microwd.es 

# Project 2: Analyze eating habits in Belgium
**Determine how healthy the different products are. This requires making and tracking decisions, hypotheses and considerations.**

Also, resolve the following queries:
* Find the oldest product
* Find the newest product
* Average product age, where age means how long the product has been in the system.
* List of other countries where products are sold too.
* Identify category of products and the compute:
* Number of products by category
* List containing names of products by category 
* Identify traces and compute:
* Number of products by trace
* List containing names of products by trace
* Data quality analysis on fields of interest (see appendix 1):
* Number of products with complete info.
* % of products without complete analysis per 100g
* % of products without additives info
* % of products without traces info
* Data profiling on fields of interest (see appendix 1):
* Stats on analysis per 100g fields
